version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: fashion_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fashion_backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongo:27017/fashion-ecommerce
      - JWT_SECRET=supersecretjwtkey123!@#
      - JWT_EXPIRE=30d
      - NODE_ENV=development
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: fashion_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
